spring:
  application:
    name: shortcut
  #  threads:
  #    virtual:
  #      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: test-group
#    producer:
#      properties:
#        batch.size: 100
#    listener:
#      ack-mode: MANUAL_IMMEDIATE

#logging.level:
 # org.springframework.kafka: info
